// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/startkit/echo.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Omo.Msa.Startkit {
  public static partial class Echo
  {
    static readonly string __ServiceName = "omo.msa.startkit.Echo";

    static readonly grpc::Marshaller<global::Omo.Msa.Startkit.Request> __Marshaller_omo_msa_startkit_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Omo.Msa.Startkit.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Omo.Msa.Startkit.Response> __Marshaller_omo_msa_startkit_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Omo.Msa.Startkit.Response.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Omo.Msa.Startkit.Ping> __Marshaller_omo_msa_startkit_Ping = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Omo.Msa.Startkit.Ping.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Omo.Msa.Startkit.Pong> __Marshaller_omo_msa_startkit_Pong = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Omo.Msa.Startkit.Pong.Parser.ParseFrom);

    static readonly grpc::Method<global::Omo.Msa.Startkit.Request, global::Omo.Msa.Startkit.Response> __Method_Call = new grpc::Method<global::Omo.Msa.Startkit.Request, global::Omo.Msa.Startkit.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Call",
        __Marshaller_omo_msa_startkit_Request,
        __Marshaller_omo_msa_startkit_Response);

    static readonly grpc::Method<global::Omo.Msa.Startkit.Ping, global::Omo.Msa.Startkit.Pong> __Method_PingPong = new grpc::Method<global::Omo.Msa.Startkit.Ping, global::Omo.Msa.Startkit.Pong>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "PingPong",
        __Marshaller_omo_msa_startkit_Ping,
        __Marshaller_omo_msa_startkit_Pong);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Omo.Msa.Startkit.EchoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Echo</summary>
    [grpc::BindServiceMethod(typeof(Echo), "BindService")]
    public abstract partial class EchoBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Omo.Msa.Startkit.Response> Call(global::Omo.Msa.Startkit.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task PingPong(grpc::IAsyncStreamReader<global::Omo.Msa.Startkit.Ping> requestStream, grpc::IServerStreamWriter<global::Omo.Msa.Startkit.Pong> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Echo</summary>
    public partial class EchoClient : grpc::ClientBase<EchoClient>
    {
      /// <summary>Creates a new client for Echo</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public EchoClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Echo that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public EchoClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected EchoClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected EchoClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Omo.Msa.Startkit.Response Call(global::Omo.Msa.Startkit.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Call(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Omo.Msa.Startkit.Response Call(global::Omo.Msa.Startkit.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Call, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Omo.Msa.Startkit.Response> CallAsync(global::Omo.Msa.Startkit.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CallAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Omo.Msa.Startkit.Response> CallAsync(global::Omo.Msa.Startkit.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Call, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Omo.Msa.Startkit.Ping, global::Omo.Msa.Startkit.Pong> PingPong(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingPong(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Omo.Msa.Startkit.Ping, global::Omo.Msa.Startkit.Pong> PingPong(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_PingPong, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override EchoClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EchoClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(EchoBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Call, serviceImpl.Call)
          .AddMethod(__Method_PingPong, serviceImpl.PingPong).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, EchoBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Call, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Omo.Msa.Startkit.Request, global::Omo.Msa.Startkit.Response>(serviceImpl.Call));
      serviceBinder.AddMethod(__Method_PingPong, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Omo.Msa.Startkit.Ping, global::Omo.Msa.Startkit.Pong>(serviceImpl.PingPong));
    }

  }
}
#endregion
