// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/msa/msa.proto

package omo_msa_startkit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StartKit service

type StartKitService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (StartKit_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (StartKit_PingPongService, error)
}

type startKitService struct {
	c    client.Client
	name string
}

func NewStartKitService(name string, c client.Client) StartKitService {
	return &startKitService{
		c:    c,
		name: name,
	}
}

func (c *startKitService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "StartKit.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *startKitService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (StartKit_StreamService, error) {
	req := c.c.NewRequest(c.name, "StartKit.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &startKitServiceStream{stream}, nil
}

type StartKit_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type startKitServiceStream struct {
	stream client.Stream
}

func (x *startKitServiceStream) Close() error {
	return x.stream.Close()
}

func (x *startKitServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *startKitServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *startKitServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *startKitServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *startKitService) PingPong(ctx context.Context, opts ...client.CallOption) (StartKit_PingPongService, error) {
	req := c.c.NewRequest(c.name, "StartKit.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &startKitServicePingPong{stream}, nil
}

type StartKit_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type startKitServicePingPong struct {
	stream client.Stream
}

func (x *startKitServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *startKitServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *startKitServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *startKitServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *startKitServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *startKitServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for StartKit service

type StartKitHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, StartKit_StreamStream) error
	PingPong(context.Context, StartKit_PingPongStream) error
}

func RegisterStartKitHandler(s server.Server, hdlr StartKitHandler, opts ...server.HandlerOption) error {
	type startKit interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type StartKit struct {
		startKit
	}
	h := &startKitHandler{hdlr}
	return s.Handle(s.NewHandler(&StartKit{h}, opts...))
}

type startKitHandler struct {
	StartKitHandler
}

func (h *startKitHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.StartKitHandler.Call(ctx, in, out)
}

func (h *startKitHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.StartKitHandler.Stream(ctx, m, &startKitStreamStream{stream})
}

type StartKit_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type startKitStreamStream struct {
	stream server.Stream
}

func (x *startKitStreamStream) Close() error {
	return x.stream.Close()
}

func (x *startKitStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *startKitStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *startKitStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *startKitStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *startKitHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.StartKitHandler.PingPong(ctx, &startKitPingPongStream{stream})
}

type StartKit_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type startKitPingPongStream struct {
	stream server.Stream
}

func (x *startKitPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *startKitPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *startKitPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *startKitPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *startKitPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *startKitPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
